### ISSUE TITLE
Rules with times set stopped working on firewall 2017-05-09 up due to kerneltz

### ISSUE THREAD

**Issue by shemgp** [k-szuster/luci-access-control#12]
As seen here: https://forum.lede-project.org/t/firewall-and-kerneltz-issues/4052/3 rules with times set don't get added to iptables because of the problem of using kerneltz.

The fix is to comment out the line `s_rule.defaults.extra = "--kerneltz"` in the file `/usr/lib/lua/luci/model/cbi/access_control.lua` on these new firewall versions.

Didn't create a pull request as I'm not sure how to make it work for both old and new firewalls.

**Comment by peppelorum** [comment]
Seeing the same behavior here, and the same fix works here too.

**Comment by k-szuster** [comment]
There is a new release available, which corrects Lede-17 problems:  0.4.2. Please upgrade.
