### ISSUE TITLE
doesn't work on LEDE Reboot 17.01.4 

### ISSUE THREAD

**Issue by Pabl0z** [k-szuster/luci-access-control#14]
there are installations issues as:
1. filename is changed after download from amazon web services by wget
2. after installation and reboot rules aren't visible in iptables and lan client are still capable to connect to internet.

**Comment by Pabl0z** [comment]
rules work in current LEDE version [LEDE Reboot 17.01.4 r3560-79f57e422d]
 - You only have to specify time in format: hh:mm:ss 
eg 20:00:00 to 07:00:00
voila ;-)

**Comment by Pabl0z** [comment]
in firewall :-/ rules because luci-access-control doesn't accept this format
<img width="1187" alt="zrzut ekranu 2018-03-09 o 13 01 09" src="https://user-images.githubusercontent.com/19762095/37206889-ca1367ea-239a-11e8-8a8b-e6ad1c5d9588.png">

<img width="954" alt="zrzut ekranu 2018-03-09 o 13 02 04" src="https://user-images.githubusercontent.com/19762095/37206904-d5ca0fda-239a-11e8-9e40-86172a054360.png">

<img width="779" alt="zrzut ekranu 2018-03-09 o 13 02 35" src="https://user-images.githubusercontent.com/19762095/37206916-dd52f5c8-239a-11e8-9976-f8073d5e1b25.png">

**Comment by k-szuster** [comment]
I'm working on adopting to owrt/lede 17 version. Give me a few days.

**Comment by k-szuster** [comment]
There is a new release available, which corrects Lede-17 problems:  0.4.2. Please upgrade.
