### ISSUE TITLE
can not unblock a device

### ISSUE THREAD

**Issue by forestforever** [k-szuster/luci-access-control#15]
Hi, 
Thank you for creating this great add-on! It has been working really well until recent weeks. First, I started to notice it would block my Roku TV completely without adopting the time set by me. I used the ticket to resolve the issue. No big deal. However, today, after I added one android phone to the access control, my kid's computer got blocked completely instead. I deleted it from the access control list, which doesn't help at all. I found that only after I uncheck the globe setting "enabled" box, my kid's computer can get back on the internet. If I check the box again, the computer will be blocked again. Changing block time, or issuing a ticket won't work.  I am wondering as it is not  even on the access control list anymore (as I deleted it), how come I just can't unblock it? Can you help? Thanks! #

**Comment by k-szuster** [comment]
Maybe after time shift, there is wrong time setting in you router?  
Could you show the screen shot of network/taffic-rules and run on the router's console:
cat /etc/config/firewall
iptables -L -v

**Comment by forestforever** [comment]
![image](https://user-images.githubusercontent.com/37254348/38010486-34ece81c-320e-11e8-9b47-3f4fbc7aecf6.png)

**Comment by forestforever** [comment]
![image](https://user-images.githubusercontent.com/37254348/38010551-70185700-320e-11e8-9fec-1ca042bd766f.png)

**Comment by forestforever** [comment]
![image](https://user-images.githubusercontent.com/37254348/38010591-a9822d90-320e-11e8-91e9-32080f5b9b08.png)

**Comment by forestforever** [comment]
![image](https://user-images.githubusercontent.com/37254348/38010614-cd36ad56-320e-11e8-97ec-d90c56aef70c.png)
![image](https://user-images.githubusercontent.com/37254348/38010633-e50a1c6a-320e-11e8-9ce0-1dadcb4086dd.png)

**Comment by forestforever** [comment]
![image](https://user-images.githubusercontent.com/37254348/38010698-1dc04a70-320f-11e8-94f7-8e85b12b7f90.png)
![image](https://user-images.githubusercontent.com/37254348/38010747-4f4062f6-320f-11e8-8562-340e68c2fa2d.png)
![image](https://user-images.githubusercontent.com/37254348/38010775-65a140d8-320f-11e8-88bb-dc71dc0e1db5.png)

**Comment by forestforever** [comment]
Hi, Krzysztof
Thanks for the prompt reply. Now I have to uncheck the enable box in the global setting in order to put this computer back online, and its MAC address doesn't show up in the config rules as I deleted it from the access control. My SHARP ROKU TV is still there as you can see, but the time I set doesn't really work, and it is blocked all the time when the enable box is checked unless I issue a ticket. Do you want me to post the screen shots when the enable box is checked instead? Thanks.

**Comment by k-szuster** [comment]
What I saw first, is that your TV is blocked form 4:00 to 2:00, which means:   from 4am to 2am next day.
You've got also two rules named "kids...", which were created outside access-control page. However all 3 rules are not enabled at the moment and as such, they don't appear in the iptables dump.
I'd suggest to remove both kids... rules from firewall/traffic-rules page and reenter them form access-control page to have them under your control.
PS1: you apparently use LEDE 17, which uses different time format and doesn't understand kerneltz switch, unlike earlier versions. This may cause problems. The new version is under work.
PS2: If you submit text dumps _please_ paste text from you console rather, than image. It is searchable and  much smaller.

**Comment by phantasm-sd** [comment]
I can confirm the tickets aren't unblocking the devices properly.

# cat /etc/config/firewall

config defaults
        option syn_flood '1'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'REJECT'

config zone
        option name 'lan'
        list network 'lan'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'

config zone
        option name 'wan'
        list network 'wan'
        list network 'wan6'
        option input 'REJECT'
        option output 'ACCEPT'
        option forward 'REJECT'
        option masq '1'
        option mtu_fix '1'

config forwarding
        option src 'lan'
        option dest 'wan'

config rule
        option name 'Allow-DHCP-Renew'
        option src 'wan'
        option proto 'udp'
        option dest_port '68'
        option target 'ACCEPT'
        option family 'ipv4'

config rule
        option name 'Allow-Ping'
        option src 'wan'
        option proto 'icmp'
        option icmp_type 'echo-request'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-IGMP'
        option src 'wan'
        option proto 'igmp'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-DHCPv6'
        option src 'wan'
        option proto 'udp'
        option src_ip 'fc00::/6'
        option dest_ip 'fc00::/6'
        option dest_port '546'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-MLD'
        option src 'wan'
        option proto 'icmp'
        option src_ip 'fe80::/10'
        list icmp_type '130/0'
        list icmp_type '131/0'
        list icmp_type '132/0'
        list icmp_type '143/0'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-Input'
        option src 'wan'
        option proto 'icmp'
        list icmp_type 'echo-request'
        list icmp_type 'echo-reply'
        list icmp_type 'destination-unreachable'
        list icmp_type 'packet-too-big'
        list icmp_type 'time-exceeded'
        list icmp_type 'bad-header'
        list icmp_type 'unknown-header-type'
        list icmp_type 'router-solicitation'
        list icmp_type 'neighbour-solicitation'
        list icmp_type 'router-advertisement'
        list icmp_type 'neighbour-advertisement'
        option limit '1000/sec'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-Forward'
        option src 'wan'
        option dest '*'
        option proto 'icmp'
        list icmp_type 'echo-request'
        list icmp_type 'echo-reply'
        list icmp_type 'destination-unreachable'
        list icmp_type 'packet-too-big'
        list icmp_type 'time-exceeded'
        list icmp_type 'bad-header'
        list icmp_type 'unknown-header-type'
        option limit '1000/sec'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-IPSec-ESP'
        option src 'wan'
        option dest 'lan'
        option proto 'esp'
        option target 'ACCEPT'

config rule
        option name 'Allow-ISAKMP'
        option src 'wan'
        option dest 'lan'
        option dest_port '500'
        option proto 'udp'
        option target 'ACCEPT'

config include
        option path '/etc/firewall.user'

config rule
        option ac_enabled '1'
        option src '*'
        option dest 'wan'
        option proto '0'
        option target 'REJECT'
        option weekdays ' mon tue wed thu fri'
        option enabled '1'
        option name 'PS4wifi-test'
        option src_mac 'A8:47:4A:EE:E7:A1'
        option start_time '21:00:00'
        option stop_time '22:00:00'
        option ac_suspend '1525411872'

# iptables -L -v
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  lo     any     anywhere             anywhere             /* !fw3 */
  724 74379 input_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for input */
  517 59317 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED /* !fw3 */
    1    60 syn_flood  tcp  --  any    any     anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN /* !fw3 */
  137  9355 zone_lan_input  all  --  br-lan any     anywhere             anywhere             /* !fw3 */
   70  5707 zone_wan_input  all  --  eth1   any     anywhere             anywhere             /* !fw3 */

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 322K  418M forwarding_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for forwarding */
   24  1501 zone_wan_dest_REJECT  all  --  any    any     anywhere             anywhere             MAC A8:47:4A:EE:E7:A1 TIME from 21:00:00 to 22:00:00 on Mon,Tue,Wed,Thu,Fri /* !fw3: PS4wifi-test */
22123 1426K zone_lan_forward  all  --  br-lan any     anywhere             anywhere             /* !fw3 */
 145K  216M zone_wan_forward  all  --  eth1   any     anywhere             anywhere             /* !fw3 */
 145K  216M ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 reject     all  --  any    any     anywhere             anywhere             /* !fw3 */

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  any    lo      anywhere             anywhere             /* !fw3 */
  762  130K output_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for output */
  499  112K ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED /* !fw3 */
    3   775 zone_lan_output  all  --  any    br-lan  anywhere             anywhere             /* !fw3 */
  260 17104 zone_wan_output  all  --  any    eth1    anywhere             anywhere             /* !fw3 */

Chain forwarding_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain forwarding_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain forwarding_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain input_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain input_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain input_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain output_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain output_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain output_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain reject (3 references)
 pkts bytes target     prot opt in     out     source               destination
   90  7064 REJECT     tcp  --  any    any     anywhere             anywhere             /* !fw3 */ reject-with tcp-reset
    0     0 REJECT     all  --  any    any     anywhere             anywhere             /* !fw3 */ reject-with icmp-port-unreachable

Chain syn_flood (1 references)
 pkts bytes target     prot opt in     out     source               destination
    1    60 RETURN     tcp  --  any    any     anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN limit: avg 25/sec burst 50 /* !fw3 */
    0     0 DROP       all  --  any    any     anywhere             anywhere             /* !fw3 */

Chain zone_lan_dest_ACCEPT (4 references)
 pkts bytes target     prot opt in     out     source               destination
    3   775 ACCEPT     all  --  any    br-lan  anywhere             anywhere             /* !fw3 */

Chain zone_lan_forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
22123 1426K forwarding_lan_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for forwarding */
22123 1426K zone_wan_dest_ACCEPT  all  --  any    any     anywhere             anywhere             /* !fw3: forwarding lan -> wan */
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate DNAT /* !fw3: Accept port forwards */
    0     0 zone_lan_dest_ACCEPT  all  --  any    any     anywhere             anywhere             /* !fw3 */

Chain zone_lan_input (1 references)
 pkts bytes target     prot opt in     out     source               destination
  137  9355 input_lan_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for input */
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate DNAT /* !fw3: Accept port redirections */
  137  9355 zone_lan_src_ACCEPT  all  --  any    any     anywhere             anywhere             /* !fw3 */

Chain zone_lan_output (1 references)
 pkts bytes target     prot opt in     out     source               destination
    3   775 output_lan_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for output */
    3   775 zone_lan_dest_ACCEPT  all  --  any    any     anywhere             anywhere             /* !fw3 */

Chain zone_lan_src_ACCEPT (1 references)
 pkts bytes target     prot opt in     out     source               destination
  137  9355 ACCEPT     all  --  br-lan any     anywhere             anywhere             ctstate NEW,UNTRACKED /* !fw3 */

Chain zone_wan_dest_ACCEPT (2 references)
 pkts bytes target     prot opt in     out     source               destination
  117  5316 DROP       all  --  any    eth1    anywhere             anywhere             ctstate INVALID /* !fw3: Prevent NAT leakage */
22266 1438K ACCEPT     all  --  any    eth1    anywhere             anywhere             /* !fw3 */

Chain zone_wan_dest_REJECT (2 references)
 pkts bytes target     prot opt in     out     source               destination
   24  1501 reject     all  --  any    eth1    anywhere             anywhere             /* !fw3 */

Chain zone_wan_forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
 145K  216M forwarding_wan_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for forwarding */
    0     0 zone_lan_dest_ACCEPT  esp  --  any    any     anywhere             anywhere             /* !fw3: Allow-IPSec-ESP */
    0     0 zone_lan_dest_ACCEPT  udp  --  any    any     anywhere             anywhere             udp dpt:isakmp /* !fw3: Allow-ISAKMP */
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate DNAT /* !fw3: Accept port forwards */
 145K  216M zone_wan_dest_REJECT  all  --  any    any     anywhere             anywhere             /* !fw3 */

Chain zone_wan_input (1 references)
 pkts bytes target     prot opt in     out     source               destination
   70  5707 input_wan_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for input */
    0     0 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:bootpc /* !fw3: Allow-DHCP-Renew */
    0     0 ACCEPT     icmp --  any    any     anywhere             anywhere             icmp echo-request /* !fw3: Allow-Ping */
    4   144 ACCEPT     igmp --  any    any     anywhere             anywhere             /* !fw3: Allow-IGMP */
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate DNAT /* !fw3: Accept port redirections */
   66  5563 zone_wan_src_REJECT  all  --  any    any     anywhere             anywhere             /* !fw3 */

Chain zone_wan_output (1 references)
 pkts bytes target     prot opt in     out     source               destination
  260 17104 output_wan_rule  all  --  any    any     anywhere             anywhere             /* !fw3: user chain for output */
  260 17104 zone_wan_dest_ACCEPT  all  --  any    any     anywhere             anywhere             /* !fw3 */

Chain zone_wan_src_REJECT (1 references)
 pkts bytes target     prot opt in     out     source               destination
   66  5563 reject     all  --  eth1   any     anywhere             anywhere             /* !fw3 */
