### ISSUE TITLE
Parameter --kerneltz not working

### ISSUE THREAD

**Issue by bouwew** [k-szuster/luci-access-control#2]
Hi,

First off, thank you for providing this nice tool!

I've been testing a little bit, and I noticed that the timing is not correct; I need to use a 1 hour offset (UTC-time?) to get it working on the times I want. I guess the use of the above parameter does not function (in my case?)

I'm on trunk, r48259, arokh's build for the WDR4900.

**Comment by k-szuster** [comment]
I know about the problem. It  arrived with OpenWrt CC. There is probably a bug in new kernel/iptables. My program works proerly on BB. 
It's no easy way to fix the iptables bug in my soft, so let's be patient and wait for next release of OpenWrt.

**Comment by bouwew** [comment]
Ok, thanks for letting me know :)

**Comment by baipesho2** [comment]
Hi Krzysztof. Thank you for creating this app, could be very useful for parental control. I am with CC 15.05.1. I can not have it working for some reason. It changes the firewall settings and creates entry there, but it still does not block the access. I am wondering if this is same issue as described above from Bouwew. If I have to do 1 Hrs offset, in which direction it should be? I am UTC-5 Eastern time.Thanks

**Comment by k-szuster** [comment]
Presumably the CC kernel problem is not fixed yet.
You should set times in UTC zone. It you want to set 12:00 local time, you need to enter 7:00.

**Comment by baipesho2** [comment]
Hi Krzysztof,

I found that 

iptables -I forwarding_rule -m comment --comment "Shut off XXX's BB10" -p all -m mac --mac-source XX:XX:XX:XX:XX:XX -m time --kerneltz --weekdays 1,2,3,4,5,7 --timestart 20:00 --timestop 23:59 -j REJECT

works for me. I put it in firewall.user and restart firewall.  Looks like –kerneltz is not the problem. It takes my router time,which is UTC-5hrs( Eeastern Standart time).

I am with Chaos Calmer 15.05.1

Thanks,

Lyudmil
