### ISSUE TITLE
Add command-line interface

### ISSUE THREAD

**Issue by edgimar** [k-szuster/luci-access-control#23]
It would be great if there were a shell or lua script that provided a command-line interface to be able to perform some or all of the actions that can be performed via luci.  Why?  Because this would enable tickets to be created, or rules to be enabled/disabled programatically from a shell script (which could be run via ssh).  This would make it easy to control AC via a smart-phone, etc.  (e.g. with the [Mercury-SSH](https://f-droid.org/en/packages/it.skarafaz.mercury/) app).

Instead of a shell / lua script, probably just making it possible to control and configure AC via [UCI](https://openwrt.org/docs/guide-user/base-system/uci) would be enough.

**Comment by k-szuster** [comment]
The software doesn't contain scripts to be run from CLI. You always may use UCI. If you look at /etc/config/firewall, you'll see, how are AC rules like. However creating/modifying tules with plain UCI would be cumbersome. You'd better make some simple scripts that meet your particular needs.
Personally, I use LUCI to control my router remotely. A smartphone with a web browser is just right.

**Comment by edgimar** [comment]
Can you explain which command-line commands would be required to enable and disable AC?  I have tried the following to disable, without success:
```
uci set firewall.@rule[9].ac_enabled=0
uci commit
/etc/init.d/firewall restart
```
Likewise, if I've turned AC off from the LEDE interface, and then try the above commands, but set `...ac_enabled=1`, it also does not seem to enable AC.  What am I missing?
