### ISSUE TITLE
UTC times for BB ? or just CC ?

### ISSUE THREAD

**Issue by tim-field** [k-szuster/luci-access-control#8]
Hi thanks for creating this.

I'm not clear after reading the readme, if I have to enter UTC times if I'm running BB, or only if I'm running CC.

Thanks

**Comment by k-szuster** [comment]
BB understands  local time; CC does not, it needs UTC.

**Comment by tim-field** [comment]
ok so it needs UTC, even if you are running BB :)

**Comment by k-szuster** [comment]
Wrong. 
BB needs  local time, NOT UTC.
Please, see README.
