### ISSUE TITLE
Option proto is being set to '0'

### ISSUE THREAD

**Issue by brightlightapps** [k-szuster/luci-access-control#9]
Seems to be a bug with option proto value being generated as '0' instead of 'all'.   The controls only worked for me when I manually changed the value from '0' to 'all' in the firewall configuration.

option proto '0'  -- not working
option proto 'all' -- works

**Comment by k-szuster** [comment]
OpenWrt reference says, that 0 and 'all' are synonyms. After all, the program does work for everybody else. 
What version of OpenWrt do you use?
